quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=jobtrail
quarkus.datasource.password=jobtrail
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/jobtrail

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true