quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=jobtrail
quarkus.datasource.password=jobtrail
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/jobtrail

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# --- JWT : vérification des tokens entrants (smallrye-jwt) ---
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://jobtrail.dev/issuer

# --- JWT : signature des tokens émis (smallrye-jwt-build) ---
smallrye.jwt.sign.key.location=privateKey.pem
